/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.chuyenmanhinhcontroller;

/**
 *
 * @author lehie
 */
public class FindbookJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FindbookJPanel
     */
    public FindbookJPanel() {
        initComponents();
        chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPanel_viewtk);
        controller.setview(new TKCBJPanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_viewtk = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Jcbtk = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel_viewtkLayout = new javax.swing.GroupLayout(jPanel_viewtk);
        jPanel_viewtk.setLayout(jPanel_viewtkLayout);
        jPanel_viewtkLayout.setHorizontalGroup(
            jPanel_viewtkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_viewtkLayout.setVerticalGroup(
            jPanel_viewtkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        Jcbtk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tìm kiếm cơ bản", "Tìm kiếm nâng cao" }));
        Jcbtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbtkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jcbtk, 0, 205, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Jcbtk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
            .addComponent(jPanel_viewtk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_viewtk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JcbtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbtkActionPerformed
        int index = Jcbtk.getSelectedIndex();
        if(index == 0)
            {
                chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPanel_viewtk);
                controller.setview(new TKCBJPanel());
            }
            if(index == 1)
            {
                chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPanel_viewtk);
                controller.setview(new TKNCJPanel());
            }
    }//GEN-LAST:event_JcbtkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jcbtk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_viewtk;
    // End of variables declaration//GEN-END:variables
}
