/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.chuyenmanhinhcontroller;
import controller.thoat;
import java.awt.BorderLayout;

/**
 *
 * @author lehie
 */
public class main_view extends javax.swing.JFrame {
      
    /**
     * Creates new form main_view
     */
    String tk,mk;
    
    public main_view(String mmq,String tk,String mk) {        
        initComponents();
        setTitle("NHÀ SÁCH TRI THỨC");
        jPnview.removeAll();
        jPnview.setLayout(new BorderLayout());
        jPnview.add(new background());
        jPnview.validate();
        jPnview.repaint();
        this.tk = tk;
        this.mk = mk;
        if(mmq.equals("NV")){
            jbtqlnv.setVisible(false);
            jbtqlnd.setVisible(false);
            jbtqls.setVisible(false);
            jbttk.setVisible(false);
            jbtqlk.setVisible(false);
        }
        else if(mmq.equals("QK")){
            jbtqlnv.setVisible(false);
            jbtqlnd.setVisible(false);
            jbtqls.setVisible(false);
            jbttk.setVisible(false);
        }
        else if(mmq.equals("QL")){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnview = new javax.swing.JPanel();
        jPnmenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtbansach = new javax.swing.JButton();
        jbtqls = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbtqlk = new javax.swing.JButton();
        jbtts = new javax.swing.JButton();
        jbtqlnd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtqlnv = new javax.swing.JButton();
        jbttk = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPnviewLayout = new javax.swing.GroupLayout(jPnview);
        jPnview.setLayout(jPnviewLayout);
        jPnviewLayout.setHorizontalGroup(
            jPnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        jPnviewLayout.setVerticalGroup(
            jPnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPnmenu.setBackground(new java.awt.Color(153, 255, 204));

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NSTT1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbtbansach.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtbansach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping.png"))); // NOI18N
        jbtbansach.setText("BÁN SÁCH");
        jbtbansach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtbansachActionPerformed(evt);
            }
        });

        jbtqls.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtqls.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconsach.png"))); // NOI18N
        jbtqls.setText("QUẢN LÝ SÁCH");
        jbtqls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtqlsActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/passkey_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton4.setText("ĐỔI MẬT KHẨU");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jbtqlk.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtqlk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/warehouse_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jbtqlk.setText("QUẢN LÝ KHO");
        jbtqlk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtqlkActionPerformed(evt);
            }
        });

        jbtts.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jbtts.setText("TÌM SÁCH");
        jbtts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttsActionPerformed(evt);
            }
        });

        jbtqlnd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtqlnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/passkey_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jbtqlnd.setText("QUẢN LÝ NGƯỜI DÙNG");
        jbtqlnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtqlndActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/kisspng-new-testament-chapter-by-chapter-old-testament-lo-5b318e1c163d23.1472976915299743000911.png"))); // NOI18N
        jLabel2.setText("Nhà sách tri thức");

        jbtqlnv.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtqlnv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/accessibility_new_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jbtqlnv.setText("QUẢN LÝ NHÂN VIÊN");
        jbtqlnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtqlnvActionPerformed(evt);
            }
        });

        jbttk.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbttk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tk.png"))); // NOI18N
        jbttk.setText("THỐNG KÊ");
        jbttk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttkActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("THOÁT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnmenuLayout = new javax.swing.GroupLayout(jPnmenu);
        jPnmenu.setLayout(jPnmenuLayout);
        jPnmenuLayout.setHorizontalGroup(
            jPnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPnmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbttk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtqls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtbansach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtqlk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtqlnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtqlnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPnmenuLayout.setVerticalGroup(
            jPnmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnmenuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtbansach, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtts, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtqls, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtqlk, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtqlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtqlnd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbttk, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtbansachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtbansachActionPerformed
        chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPnview);
        controller.setview(new BansachJPanel());
    }//GEN-LAST:event_jbtbansachActionPerformed

    private void jbtqlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtqlsActionPerformed
        chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPnview);
        controller.setview(new UpdatebookJPanel());
    }//GEN-LAST:event_jbtqlsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPnview);
        controller.setview(new DoipassJPanel(tk,mk));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbtqlkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtqlkActionPerformed
        chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPnview);
        controller.setview(new QLKSJPanel());
    }//GEN-LAST:event_jbtqlkActionPerformed

    private void jbttsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttsActionPerformed
        chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPnview);
        controller.setview(new FindbookJPanel());
    }//GEN-LAST:event_jbttsActionPerformed

    private void jbtqlndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtqlndActionPerformed
        chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPnview);
        controller.setview(new UserJPanel());
    }//GEN-LAST:event_jbtqlndActionPerformed

    private void jbtqlnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtqlnvActionPerformed
        chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPnview);
        controller.setview(new QLNVJPanel());
    }//GEN-LAST:event_jbtqlnvActionPerformed

    private void jbttkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttkActionPerformed
        chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPnview);
        controller.setview(new ThongKeJPanel());
    }//GEN-LAST:event_jbttkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        thoat t = new thoat();
        t.btthoat();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnmenu;
    private javax.swing.JPanel jPnview;
    private javax.swing.JButton jbtbansach;
    private javax.swing.JButton jbtqlk;
    private javax.swing.JButton jbtqlnd;
    private javax.swing.JButton jbtqlnv;
    private javax.swing.JButton jbtqls;
    private javax.swing.JButton jbttk;
    private javax.swing.JButton jbtts;
    // End of variables declaration//GEN-END:variables
}
